# Generated by Django 4.1.7 on 2023-03-04 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('STUDENTS', 'Students'), ('PARENTS', 'Parents'), ('TEACHERS', 'Teachers')], default='STUDENTS', max_length=50)),
                ('name', models.CharField(max_length=350)),
                ('designation', models.CharField(blank=True, max_length=350, null=True)),
                ('message', models.TextField()),
                ('rating', models.CharField(choices=[('1', 'One Star'), ('2', 'Two Stars'), ('3', 'Three Stars'), ('4', 'Four Stars'), ('5', 'Five Stars')], default='5', max_length=50)),
                ('image', models.ImageField(upload_to='testimonial/%Y/%m/%d/')),
                ('is_draft', models.BooleanField(default=False)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
