# Generated by Django 4.1.7 on 2023-03-15 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('achievers', '0005_alter_result_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievers_categories_uploaded', to=settings.AUTH_USER_MODEL),
        ),
    ]
