# Generated by Django 4.1.7 on 2023-03-05 10:09

import ckeditor_uploader.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=350)),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('is_draft', models.BooleanField(default=False)),
                ('meta_title', models.TextField(blank=True, null=True)),
                ('og_title', models.TextField(blank=True, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('og_description', models.TextField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_course_category', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=350)),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True)),
                ('breif_description', models.TextField()),
                ('detail', ckeditor_uploader.fields.RichTextUploadingField()),
                ('banner', models.ImageField(upload_to='courses/%Y/%m/%d/')),
                ('actual_price', models.PositiveBigIntegerField()),
                ('discount_in_percentage', models.PositiveBigIntegerField(blank=True, null=True)),
                ('discounted_price', models.PositiveBigIntegerField(blank=True, null=True)),
                ('publish_on', models.DateField(blank=True, default=datetime.date.today)),
                ('is_draft', models.BooleanField(default=False)),
                ('meta_title', models.TextField(blank=True, null=True)),
                ('og_title', models.TextField(blank=True, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('og_description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_category', to='courses.category')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
