# Generated by Django 4.1.7 on 2023-03-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='breif_description',
        ),
        migrations.AddField(
            model_name='course',
            name='brief_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
