# Generated by Django 4.1.7 on 2023-03-05 09:29

import ckeditor_uploader.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_title', models.CharField(max_length=350)),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True)),
                ('event_detail', ckeditor_uploader.fields.RichTextUploadingField()),
                ('event_for', models.CharField(choices=[('FOR_KIDS', 'Kids'), ('FOR_ADULTS', 'Adults')], default='FOR_ADULTS', max_length=50)),
                ('event_banner', models.ImageField(upload_to='events/%Y/%m/%d/')),
                ('event_location', models.CharField(max_length=350)),
                ('phone', models.CharField(max_length=350)),
                ('event_website', models.CharField(max_length=350)),
                ('event_organizer', models.CharField(max_length=350)),
                ('event_date', models.DateField(blank=True, default=datetime.date.today)),
                ('event_time', models.TimeField(blank=True, default=datetime.datetime(2023, 3, 5, 9, 29, 42, 994374, tzinfo=datetime.timezone.utc))),
                ('publish_on', models.DateField(blank=True, default=datetime.date.today)),
                ('is_draft', models.BooleanField(default=False)),
                ('meta_title', models.TextField(blank=True, null=True)),
                ('og_title', models.TextField(blank=True, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('og_description', models.TextField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
