# Generated by Django 4.1.7 on 2023-03-05 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2023, 3, 5, 15, 0, 40, 876678)),
        ),
    ]
