# Generated by Django 4.1.7 on 2023-03-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_tips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experttip',
            name='slug',
            field=models.SlugField(blank=True, max_length=350, unique=True),
        ),
        migrations.AlterField(
            model_name='experttip',
            name='title',
            field=models.CharField(max_length=350),
        ),
    ]
