# Generated by Django 4.1.7 on 2023-03-15 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expert_tips', '0003_experttip_brief_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experttip',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_tips_uploaded', to=settings.AUTH_USER_MODEL),
        ),
    ]
