# Generated by Django 4.1.7 on 2023-03-05 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='branch',
            field=models.CharField(blank=True, choices=[('VIJAYNAGAR', 'Vijaynagar'), ('HEBBAL', 'Hebbal'), ('KANAKAPURA_ROAD', 'Kanakapura Road')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 3, 5, 16, 6, 18, 768880)),
        ),
    ]
