# Generated by Django 4.1.7 on 2023-03-15 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0009_alter_enquiry_course_alter_enquiry_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 3, 16, 0, 10, 56, 345653)),
        ),
    ]
