# Generated by Django 4.1.7 on 2023-03-15 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0012_alter_enquiry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 3, 16, 0, 12, 51, 865783)),
        ),
    ]
